import { Link } from 'react-router-dom';
import { WHAT_IS_STORED } from './stored-data';

const page: React.CSSProperties = {
  maxWidth: 760,
  margin: '0 auto',
  padding: '48px 24px 96px',
  lineHeight: 1.6,
};

export default function DataNotice() {
  return (
    <div style={page}>
      <p style={{ marginBottom: 32 }}>
        <Link to="/" style={{ color: '#2563eb' }}>← Back</Link>
      </p>

      <h1 style={{ fontSize: 32, marginBottom: 8 }}>What this stores about you</h1>
      <p style={{ color: '#4b5563', marginTop: 0 }}>
        This is an experimental learning platform being tested with consenting adults.
        It is not yet suitable for children, and this notice is not a substitute for the
        privacy documentation a service for minors would need.
      </p>

      <h2 style={{ fontSize: 22, marginTop: 40 }}>What is kept</h2>
      {WHAT_IS_STORED.map(entry => (
        <div key={entry.table} style={{ marginBottom: 20 }}>
          <p style={{ margin: '0 0 4px', fontWeight: 600 }}>{entry.what}</p>
          <p style={{ margin: 0, color: '#4b5563' }}>{entry.why}</p>
        </div>
      ))}

      <h2 style={{ fontSize: 22, marginTop: 40 }}>Two things worth saying plainly</h2>
      <p>
        <strong>The system forms judgements about you.</strong> From how fast you answer
        and how you move through a quiz, it infers things like whether you were guessing
        or had stopped paying attention, and those inferences change what you are shown
        next. They are recorded with the signals behind them, and you can disagree with
        them.
      </p>
      <p>
        <strong>Your conversations go to a language model.</strong> Tutor and coach
        replies are generated by a third-party model provider, which means the text of
        those conversations leaves this server.
      </p>

      <h2 style={{ fontSize: 22, marginTop: 40 }}>What is not here yet</h2>
      <p style={{ color: '#4b5563' }}>
        There is no self-service export or deletion yet, and no defined retention period —
        data stays until someone removes it by hand. Ask, and it will be deleted. Both are
        being built, and both would have to exist before this is used by anyone who is not
        a consenting adult.
      </p>
    </div>
  );
}
